DSOURCE = mainD.cpp dFlags.cpp dFlags.h Disp.cpp Disp.cpp
NSOURCE = mainN.cpp nFlags.cpp nFlags.h Nsub.cpp Nsub.h
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

disp: $(DSOURCE)
	$(CC) $(LFALGS) $(DSOURCE) -o disp

nsub: $(NSOURCE)
	$(CC) $(LFALGS) $(NSOURCE) -o nsub
	
clean:
	\rm *.o *~ disp nsub
	
	

