DISPSRC = bitdisp.cpp 
TRANSRC = bitrans.cpp
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

all: bitdisp bitrans

bitdisp: $(DISPSRC)
	$(CC) $(LFALGS) $(DISPSRC) -o bitdisp

bitrans: $(TRANSRC)
	$(CC) $(LFALGS) $(TRANSRC) -o bitrans
	
clean:
	\rm *.o *~ bitdisp bitrans