PSOURCE = main.cpp pFlag.cpp pFlag.h Pad.cpp Pad.h
CC = g++
CFLAGS = -g -Wall -c
LFLAGS = -g -std=gnu++11 -Wall

pad: $(PSOURCE)
	$(CC) $(LFLAGS) $(PSOURCE) -o pad

toss: 
	\rm *.pad

clean:
	\rm *.pad *.upad pad
	
	
